# -*- coding: utf-8 -*-
"""realtime_stabilization_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uDfQE6NrH5zIFdBOh4OqPFds2iqvoQ2y

# Real-time video stabilization

Causal stabilization for a camera on a moving platform. The pipeline never looks
at a future frame, so it runs on a live stream with no added latency. Target
hardware is a Jetson Orin NX; a synchronized stereo pair is the next step.

| section | what it covers |
|---|---|
| A. Setup | definitions, run once per session |
| B. Benchmarks | three handheld clips, one shared config |
| C. Target profile | drone footage with injected narrow-band vibration |
| D. Deployment | what changes on the device |
| Appendix | the experiments the settings came from |

**The short version.** On the handheld benchmarks suppression lands around
65-70%. On drone footage with the kind of narrow-band vibration a rotor
produces, it reaches 92-95%. The difference is not the code: a human hand shakes
across a broad band that overlaps the motion we have to keep, which is the
hardest case an IIR low-pass can face. The handheld numbers are a pessimistic
floor for the actual application.

---
## A. Setup

Three definition cells. Run once per session.

### A1. Core stabilizer

The only part that ships to the device.
"""

# Core stabilizer: corner-based budget, soft limiting,
# grid-distributed features, confidence weighting.
"""
Causal video stabilization for live streams.

Design notes
------------
1) No future frames. process() only ever sees what has already arrived.
   Trajectory smoothing is an EMA (IIR), not a sliding window, so the
   output frame is produced immediately with zero added latency.
2) Sources are pluggable. VideoFileSource for offline work today,
   CsiCameraSource on the Jetson tomorrow; nothing else changes.
3) Built with stereo in mind. Every frame carries a timestamp, a camera
   id and the warp that was applied. process() also accepts an
   external_correction so a future sync layer can force both cameras to
   use the *same* correction -- stabilizing two cameras independently
   would break the stereo geometry.
4) Speed. Motion is estimated on a downscaled grayscale frame; rotation,
   translation and the crop-zoom all go into a single warpAffine.
"""
from __future__ import annotations
import math, os, time
from dataclasses import dataclass
from typing import Iterator, Optional, Tuple, List
import cv2
import numpy as np


@dataclass
class Frame:
    image: np.ndarray
    timestamp: float
    index: int
    cam_id: int = 0


@dataclass
class Motion:
    dx: float = 0.0
    dy: float = 0.0
    da: float = 0.0          # radians
    valid: bool = False
    n_inliers: int = 0
    def as_array(self):
        return np.array([self.dx, self.dy, self.da], dtype=np.float64)


@dataclass
class StabilizedFrame:
    image: np.ndarray
    timestamp: float
    index: int
    cam_id: int
    correction: np.ndarray
    motion: Motion
    warp: np.ndarray
    n_tracks: int
    proc_ms: float


@dataclass
class StabConfig:
    proc_width: int = 480          # motion-estimation width; biggest speed lever
    max_corners: int = 200
    quality_level: float = 0.01
    min_distance: int = 12
    block_size: int = 3
    redetect_interval: int = 15
    min_tracks: int = 60
    lk_win: int = 21
    lk_levels: int = 3
    use_fb_check: bool = True      # forward-backward check (~20% slower)
    fb_threshold: float = 1.0
    ransac_thresh: float = 3.0
    min_inliers: int = 12
    # Defaults come from the benchmark sweep (see the appendix notebook).
    # adaptive=True was measured to fire almost constantly and wreck the
    # smoothing, so it is off by default. It may still help on footage with
    # fast sustained panning -- check visually before turning it back on.
    smooth_alpha: float = 0.90     # 0.85 = responsive, 0.97 = very smooth
    adaptive: bool = False
    crop_ratio: float = 0.12       # crop per side; zoom = 1/(1-2r)
    grid: int = 4                  # feature distribution grid
    conf_inliers: int = 40         # inlier count for full confidence
    windup_leak: float = 0.25      # anti-windup leak rate
    max_angle_deg: float = 3.0
    safety: float = 0.95           # unused since the corner check replaced it
    num_threads: int = 0
    interpolation: int = cv2.INTER_LINEAR
    border_mode: int = cv2.BORDER_REPLICATE


class FrameSource:
    def read(self) -> Optional[Frame]:
        raise NotImplementedError
    def release(self): pass
    def __iter__(self):
        while True:
            f = self.read()
            if f is None: break
            yield f


class VideoFileSource(FrameSource):
    """Reads a file but behaves like a camera: no seeking, no look-ahead."""
    def __init__(self, path, cam_id=0, realtime=False):
        if not os.path.exists(path):
            raise FileNotFoundError(f"Dosya bulunamadi: {path}")
        self.cap = cv2.VideoCapture(path)
        if not self.cap.isOpened():
            raise IOError(f"Video acilamadi (codec?): {path}")
        self.cam_id, self.realtime, self.index = cam_id, realtime, -1
        self.fps = self.cap.get(cv2.CAP_PROP_FPS) or 30.0
        self.width = int(self.cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        self.height = int(self.cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        self._t0 = time.monotonic()

    def read(self):
        ok, img = self.cap.read()
        if not ok: return None
        self.index += 1
        ts = self.index / self.fps
        if self.realtime:
            d = (self._t0 + ts) - time.monotonic()
            if d > 0: time.sleep(d)
        return Frame(img, ts, self.index, self.cam_id)

    def release(self): self.cap.release()


class CsiCameraSource(FrameSource):
    """Jetson CSI camera. Won't run off-device; here so deployment is a no-op."""
    GST = ("nvarguscamerasrc sensor-id={sid} ! "
           "video/x-raw(memory:NVMM), width={w}, height={h}, framerate={fps}/1 ! "
           "nvvidconv ! video/x-raw, format=BGRx ! "
           "videoconvert ! video/x-raw, format=BGR ! "
           "appsink drop=true max-buffers=1 sync=false")

    def __init__(self, sensor_id=0, width=1920, height=1080, fps=30, cam_id=None):
        self.cap = cv2.VideoCapture(
            self.GST.format(sid=sensor_id, w=width, h=height, fps=fps),
            cv2.CAP_GSTREAMER)
        if not self.cap.isOpened():
            raise IOError(f"CSI kamera acilamadi (sensor-id={sensor_id})")
        self.cam_id = sensor_id if cam_id is None else cam_id
        self.index = -1

    def read(self):
        ok, img = self.cap.read()
        if not ok: return None
        self.index += 1
        return Frame(img, time.monotonic(), self.index, self.cam_id)

    def release(self): self.cap.release()


class OnlineStabilizer:
    """
    frame -> downscale + gray -> LK tracking -> partial affine (RANSAC)
          -> cumulative trajectory -> EMA -> correction -> limit -> one warp
    """
    def __init__(self, cfg: StabConfig = StabConfig(), cam_id: int = 0):
        self.cfg, self.cam_id = cfg, cam_id
        if cfg.num_threads > 0: cv2.setNumThreads(cfg.num_threads)
        cv2.setUseOptimized(True)
        self._lk = dict(winSize=(cfg.lk_win, cfg.lk_win), maxLevel=cfg.lk_levels,
                        criteria=(cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 20, 0.03))
        self.reset()

    def reset(self):
        self.prev_gray = None
        self.prev_pts = None
        self.traj = np.zeros(3)
        self.smooth = np.zeros(3)
        self.frame_count = 0
        self.scale = 1.0
        self.size = None
        self._center = (0.0, 0.0)
        self._last_m = np.zeros(3)
        self._coast = 0
        self._zoom = 1.0 / (1.0 - 2.0 * self.cfg.crop_ratio)

    def _prepare(self, image):
        h, w = image.shape[:2]
        if self.size is None:
            self.size = (w, h)
            self.scale = min(1.0, self.cfg.proc_width / float(w))
            self._center = (w / 2.0, h / 2.0)
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        if self.scale < 1.0:
            gray = cv2.resize(gray, None, fx=self.scale, fy=self.scale,
                              interpolation=cv2.INTER_AREA)
        return gray

    def _detect(self, gray, keep=None):
        """Detect features with a per-cell quota.

        goodFeaturesToTrack ranks corners globally, so one high-texture
        region -- a passing car, a close-up object -- can take most of the
        budget and drag RANSAC onto *its* motion instead of the camera's.
        Passing `keep` preserves surviving tracks and only fills the gaps."""
        cfg = self.cfg
        h, w = gray.shape
        gy = gx = cfg.grid
        per = max(4, cfg.max_corners // (gx*gy))
        mask = None
        if keep is not None and len(keep):
            mask = np.full((h, w), 255, np.uint8)
            for x, y in keep.reshape(-1, 2).astype(int):
                cv2.circle(mask, (x, y), cfg.min_distance, 0, -1)
        pts = []
        for i in range(gy):
            for j in range(gx):
                y0, y1 = i*h//gy, (i+1)*h//gy
                x0, x1 = j*w//gx, (j+1)*w//gx
                sub = None if mask is None else mask[y0:y1, x0:x1]
                p = cv2.goodFeaturesToTrack(gray[y0:y1, x0:x1], per,
                        cfg.quality_level, cfg.min_distance,
                        mask=sub, blockSize=cfg.block_size)
                if p is not None:
                    p[:,0,0] += x0; p[:,0,1] += y0
                    pts.append(p)
        new = np.vstack(pts) if pts else None
        if keep is None or not len(keep):
            return new
        return keep if new is None else np.vstack([keep, new]).astype(np.float32)

    def _track(self, pg, cg, p0):
        p1, st, _ = cv2.calcOpticalFlowPyrLK(pg, cg, p0, None, **self._lk)
        if p1 is None: return None, None
        st = st.reshape(-1).astype(bool)
        if self.cfg.use_fb_check and st.any():
            pb, st2, _ = cv2.calcOpticalFlowPyrLK(cg, pg, p1, None, **self._lk)
            if pb is not None:
                err = np.linalg.norm(p0.reshape(-1, 2) - pb.reshape(-1, 2), axis=1)
                st &= st2.reshape(-1).astype(bool) & (err < self.cfg.fb_threshold)
        if st.sum() < 6: return None, None
        return p0[st], p1[st]

    def _estimate(self, p0, p1) -> Motion:
        M, inl = cv2.estimateAffinePartial2D(
            p0, p1, method=cv2.RANSAC, ransacReprojThreshold=self.cfg.ransac_thresh,
            maxIters=500, confidence=0.99, refineIters=10)
        if M is None: return Motion()
        n = int(inl.sum()) if inl is not None else 0
        if n < self.cfg.min_inliers: return Motion(n_inliers=n)
        s = 1.0 / self.scale
        return Motion(float(M[0, 2]) * s, float(M[1, 2]) * s,
                      float(math.atan2(M[1, 0], M[0, 0])), True, n)

    def _fits(self, M, W, H):
        """Do all four output corners land inside the source frame?

        Checks rotation, zoom and translation together. Limiting each axis
        separately missed the extra margin rotation eats at the corners --
        at crop=0.10 and 6 degrees the frame overflowed by ~53 px and
        BORDER_REPLICATE smeared the edges."""
        Mi = cv2.invertAffineTransform(M)
        dst = np.array([[0,0],[W,0],[W,H],[0,H]], np.float32).reshape(-1,1,2)
        q = cv2.transform(dst, Mi).reshape(-1,2)
        return (q[:,0].min() >= 0 and q[:,1].min() >= 0
                and q[:,0].max() <= W and q[:,1].max() <= H)

    def _soft_limit(self, corr, mx, my, ma, knee=0.6):
        """Squash toward the limit with tanh past a knee instead of clipping.

        np.clip has a discontinuous derivative, so every time the correction
        hit the wall its velocity dropped to zero and the picture snapped --
        the most visible artifact this stabilizer produced."""
        lim = (mx, my, ma)
        for i in range(3):
            r = abs(corr[i]) / max(lim[i], 1e-9)
            if r > knee:
                t = (r - knee) / (1 - knee)
                corr[i] *= (knee + (1 - knee) * math.tanh(t)) / r
        return corr

    def _fit_scale(self, corr):
        """Scale the correction down until the frame fits, by bisection.

        This used to sit after the warp was built, multiplying corr by 0.85 up
        to six times. Two problems with that: the hard step undid the tanh
        limiting above it, so on clips that saturate often the smooth approach
        to the limit became a jump and the snap artifact came back; and 0.85^n
        overshoots downward, cutting about 10% more than necessary. Bisection
        lands within 0.2% and keeps the correction continuous.
        """
        if self.size is None:
            return corr
        W, H = self.size
        if self._fits(self._warp_matrix(corr), W, H):
            return corr
        lo, hi = 0.0, 1.0
        for _ in range(8):
            mid = 0.5 * (lo + hi)
            if self._fits(self._warp_matrix(corr * mid), W, H):
                lo = mid
            else:
                hi = mid
        return corr * lo

    def _smooth_step(self, mx, my):
        cfg = self.cfg
        a = cfg.smooth_alpha
        self.smooth = a * self.smooth + (1 - a) * self.traj
        corr = self.smooth - self.traj
        if cfg.adaptive:
            r = max(abs(corr[0]) / max(mx, 1e-6), abs(corr[1]) / max(my, 1e-6))
            if r > 0.7:   # track the camera faster as we approach the limit
                ae = a - (a - 0.60) * min((r - 0.7) / 0.3, 1.0)
                self.smooth = ae * self.smooth + (1 - ae) * self.traj
                corr = self.smooth - self.traj
        ma = math.radians(cfg.max_angle_deg)
        corr = self._soft_limit(corr, mx, my, ma)
        corr = self._fit_scale(corr)      # corner budget, inside the limiter
        # anti-windup: leak toward the limited value instead of snapping to it
        self.smooth += cfg.windup_leak * ((self.traj + corr) - self.smooth)
        return corr

    def _warp_matrix(self, corr):
        # Sign: estimateAffinePartial2D and getRotationMatrix2D disagree on
        # rotation direction, hence the minus. Without it the correction
        # roughly doubled the rotation instead of removing it.
        M = cv2.getRotationMatrix2D(self._center, -math.degrees(corr[2]), self._zoom)
        # The crop-zoom magnifies the image by z, so it magnifies the motion
        # inside it too. Without scaling the correction by z, a fraction
        # (z-1)/z of the shake survives -- 32% at crop=0.12.
        M[0, 2] += corr[0] * self._zoom
        M[1, 2] += corr[1] * self._zoom
        return M

    def process(self, frame: Frame, external_correction=None) -> StabilizedFrame:
        t0 = time.perf_counter()
        cfg = self.cfg
        gray = self._prepare(frame.image)
        W, H = self.size
        mx = cfg.crop_ratio * W * cfg.safety
        my = cfg.crop_ratio * H * cfg.safety

        motion = Motion()
        need = (self.prev_pts is None or len(self.prev_pts) < cfg.min_tracks
                or self.frame_count % cfg.redetect_interval == 0)
        if self.prev_gray is not None:
            if need: self.prev_pts = self._detect(self.prev_gray, keep=self.prev_pts)
            if self.prev_pts is not None and len(self.prev_pts) >= 6:
                p0, p1 = self._track(self.prev_gray, gray, self.prev_pts)
                if p0 is not None:
                    motion = self._estimate(p0, p1)
                    self.prev_pts = p1.reshape(-1, 1, 2).astype(np.float32)
                else:
                    self.prev_pts = None
            else:
                self.prev_pts = None

        if motion.valid:
    # Weight by inlier count rather than treating motion as all-or-nothing.
            # Assuming "the camera stopped" on a blurry frame made the
            # trajectory jump once tracking recovered.
            # Blend toward a constant-velocity prediction, not toward zero.
            # `traj += w * motion` looks like a confidence filter but is a
            # truncated estimate: on a frame with half the required inliers,
            # half the measured motion never reaches the trajectory. That error
            # is permanent -- traj drifts below the true camera path while the
            # warp is still applied to the real image. Measured on a synthetic
            # case: 100 px of true motion accumulated as 62 px.
            w = min(1.0, motion.n_inliers / float(cfg.conf_inliers))
            m = motion.as_array()
            est = w * m + (1.0 - w) * self._last_m
            self.traj += est
            self._last_m = 0.7 * est + 0.3 * self._last_m
            self._coast = 3
        elif self._coast > 0:
            # tracking lost: coast on last known velocity for a few frames
            # rather than asserting the camera stopped
            self.traj += self._last_m
            self._coast -= 1
        corr = self._smooth_step(mx, my)
        if external_correction is not None:
            corr = np.asarray(external_correction, dtype=np.float64)
            self.smooth = self.traj + corr

        M = self._warp_matrix(corr)            # budget already applied above
        out = cv2.warpAffine(frame.image, M, (W, H),
                             flags=cfg.interpolation, borderMode=cfg.border_mode)
        self.prev_gray = gray
        self.frame_count += 1
        return StabilizedFrame(out, frame.timestamp, frame.index, frame.cam_id,
                               corr, motion, M,
                               0 if self.prev_pts is None else len(self.prev_pts),
                               (time.perf_counter() - t0) * 1000.0)


class CameraPipeline:
    """One source + one stabilizer. The sync layer will hold two of these."""
    def __init__(self, source, cfg=StabConfig(), cam_id=0):
        self.source, self.cam_id = source, cam_id
        self.stab = OnlineStabilizer(cfg, cam_id=cam_id)
    def next(self, external_correction=None):
        f = self.source.read()
        if f is None: return None
        f.cam_id = self.cam_id
        return self.stab.process(f, external_correction=external_correction)
    def release(self): self.source.release()


print("Core loaded.")

"""### A2. Measurement helpers

"""

"""
Offline evaluation helpers. None of this ships to the Jetson -- it exists to
measure whether the stabilizer is doing its job and to pick parameters.

Two metrics live here and they answer different questions:

  measure_motion / compare_motion
      Mean frame-to-frame displacement of the output video. Includes the
      deliberate camera motion we are supposed to *keep*, so on pan-heavy
      footage it can never approach 100%. Useful, but easy to misread.

  high-frequency suppression (see hf_score)
      Removes the low-frequency component first, then compares what is left.
      This is the one that tracks what the eye calls "shaky", and it is the
      metric parameter choices should be made against.
"""

import math
import os
import subprocess
from typing import Optional
from urllib.request import urlretrieve

import cv2
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view


SAMPLES = {
    # MeshFlow (Liu et al., ECCV 2016) sample clip -- academic source, fast host
    "meshflow": ("https://raw.githubusercontent.com/sudheerachary/"
                 "Mesh-Flow-Video-Stabilization/master/data/shaky-5.avi"),
    "meshflow_small": ("https://raw.githubusercontent.com/sudheerachary/"
                       "Mesh-Flow-Video-Stabilization/master/data/small-shaky-5.avi"),
    "ostrich": "https://s3.amazonaws.com/python-vidstab/ostrich.mp4",
    "thrasher": "https://s3.amazonaws.com/python-vidstab/thrasher.mp4",
}


def download_sample(name="meshflow", dest="samples"):
    if name not in SAMPLES:
        raise ValueError(f"Unknown sample: {name}. Options: {list(SAMPLES)}")
    os.makedirs(dest, exist_ok=True)
    ext = os.path.splitext(SAMPLES[name])[1] or ".mp4"
    path = os.path.join(dest, f"{name}{ext}")
    if os.path.exists(path) and os.path.getsize(path) > 100_000:
        print(f"[cached] {path}")
        return path
    print(f"[downloading] {SAMPLES[name]}")
    urlretrieve(SAMPLES[name], path)
    c = cv2.VideoCapture(path)
    print(f"[ready] {path}  {int(c.get(3))}x{int(c.get(4))} "
          f"{c.get(5):.1f}fps {int(c.get(7))} frames "
          f"({os.path.getsize(path)/1e6:.1f} MB)")
    c.release()
    return path


def add_shake(src_path, out_path=None, amp=15.0, rot=2.0, noise=0.4,
              max_frames=300, seed=0):
    """Inject shake of known strength and save the ground truth alongside.

    The ground truth is stored as the affine parameters of the injected
    matrix, not as the raw jx/jy offsets: rotation about the centre produces
    extra translation away from the centre, and the estimator measures that
    inside tx/ty. Storing jx/jy would mean the two sides measure different
    things and the suppression numbers come out nonsensical.
    """
    rng = np.random.default_rng(seed)
    if out_path is None:
        b, e = os.path.splitext(src_path)
        out_path = f"{b}_shake_a{amp:g}_r{rot:g}{e}"   # params in the filename
    if os.path.exists(out_path) and os.path.exists(out_path + ".gt.npy"):
        print(f"[cached] {out_path}")
        return out_path, out_path + ".gt.npy"

    src = VideoFileSource(src_path)
    W, H = src.width, src.height
    w = cv2.VideoWriter(out_path, cv2.VideoWriter_fourcc(*"mp4v"), src.fps, (W, H))
    gt, i = [], 0
    while True:
        f = src.read()
        if f is None or (max_frames and i >= max_frames):
            break
        jx = amp * math.sin(i*1.7) + amp*noise*rng.standard_normal()
        jy = amp*0.8*math.sin(i*2.3) + amp*noise*rng.standard_normal()
        ja = rot * math.sin(i*1.1) + rot*noise*rng.standard_normal()
        M = cv2.getRotationMatrix2D((W/2., H/2.), ja, 1.0)
        M[0, 2] += jx
        M[1, 2] += jy
        w.write(cv2.warpAffine(f.image, M, (W, H), borderMode=cv2.BORDER_REPLICATE))
        gt.append([float(M[0, 2]), float(M[1, 2]),
                   float(math.atan2(M[1, 0], M[0, 0]))])
        i += 1
    w.release()
    src.release()
    np.save(out_path + ".gt.npy", np.array(gt))
    print(f"[generated] {out_path}  ({i} frames, amp={amp}, rot={rot})")
    return out_path, out_path + ".gt.npy"


def stabilize_clip(path, cfg=None, out_dir="out", max_frames=None,
                   side_by_side=True, to_h264=True, quiet=False):
    """Run a clip through the stabilizer one frame at a time, as if live."""
    cfg = cfg or StabConfig()
    os.makedirs(out_dir, exist_ok=True)
    name = os.path.splitext(os.path.basename(path))[0]
    tmp = os.path.join(out_dir, f"{name}_tmp.mp4")
    final = os.path.join(out_dir, f"{name}_cmp.mp4" if side_by_side
                         else f"{name}_stab.mp4")
    src = VideoFileSource(path)
    stab = OnlineStabilizer(cfg)
    W, H = src.width, src.height
    wr = cv2.VideoWriter(tmp, cv2.VideoWriter_fourcc(*"mp4v"), src.fps,
                         (W*2 if side_by_side else W, H))
    times, raw_j, stab_j, corrs = [], [], [], []
    prev = np.zeros(3)
    n = 0
    while True:
        f = src.read()
        if f is None:
            break
        sf = stab.process(f)
        times.append(sf.proc_ms)
        corrs.append(sf.correction.copy())
        if sf.motion.valid:
            raw_j.append(math.hypot(sf.motion.dx, sf.motion.dy))
            z = stab._zoom            # the zoom magnifies output motion by z
            r = z * (sf.motion.as_array() + (sf.correction - prev))
            stab_j.append(math.hypot(r[0], r[1]))
        prev = sf.correction.copy()
        wr.write(np.hstack([f.image, sf.image]) if side_by_side else sf.image)
        n += 1
        if max_frames and n >= max_frames:
            break
    wr.release()
    src.release()

    if to_h264 and subprocess.call(["ffmpeg", "-y", "-loglevel", "error", "-i", tmp,
                                    "-vcodec", "libx264", "-pix_fmt", "yuv420p",
                                    "-crf", "24", final]) == 0:
        os.remove(tmp)
    else:
        os.replace(tmp, final)

    t = np.array(times) if times else np.array([0.0])
    res = {"clip": os.path.basename(path), "res": f"{W}x{H}", "frames": n,
           "ms": float(t.mean()), "ms_p95": float(np.percentile(t, 95)),
           "fps": float(1000/t.mean()) if t.mean() else 0.0,
           "jit_raw": float(np.mean(raw_j)) if raw_j else 0.0,
           "jit_stab": float(np.mean(stab_j)) if stab_j else 0.0,
           "corrections": np.array(corrs), "times": t, "cfg": cfg, "out": final}
    if not quiet:
        red = (1 - res["jit_stab"]/res["jit_raw"])*100 if res["jit_raw"] else 0
        print(f"{res['res']} | {n} frames | {res['ms']:.2f} ms "
              f"(p95 {res['ms_p95']:.2f}) -> {res['fps']:.1f} FPS")
        print(f"jitter: {res['jit_raw']:.2f} -> {res['jit_stab']:.2f} px/frame "
              f"({red:.1f}% reduction)")
    return res


# --------------------------------------------------------------------------
# metrics
# --------------------------------------------------------------------------

def measure_motion(path, max_frames=400, half=None):
    """Frame-to-frame motion of a video on its own.

    half='right' measures only the stabilized half of a side-by-side output;
    without it half the frame is the raw footage and the number is garbage.
    """
    stab = OnlineStabilizer(StabConfig(crop_ratio=0.0, smooth_alpha=0.0))
    src = VideoFileSource(path)
    m, i = [], 0
    while i < max_frames:
        f = src.read()
        if f is None:
            break
        if half:
            w = f.image.shape[1] // 2
            f.image = f.image[:, :w] if half == "left" else f.image[:, w:]
        sf = stab.process(f)
        if sf.motion.valid:
            m.append(sf.motion.as_array())
        i += 1
    src.release()
    if not m:
        return {"dxy": 0.0, "da_std": 0.0, "frames": 0}
    m = np.array(m)
    return {"dxy": float(np.mean(np.hypot(m[:, 0], m[:, 1]))),
            "da_std": float(np.degrees(np.std(m[:, 2]))), "frames": len(m)}


def compare_motion(in_path, out_path, max_frames=400, out_half=None, out_zoom=1.0):
    """Input vs output motion.

    out_zoom must be 1/(1-2*crop_ratio). The output is zoomed, so everything
    in it -- including the camera motion we deliberately keep -- is magnified
    by z. Skip the division and results get worse as crop_ratio goes up, which
    is an artifact, not a real effect. Rotation is unaffected by zoom.
    """
    a = measure_motion(in_path, max_frames)
    b = measure_motion(out_path, max_frames, half=out_half)
    b = {**b, "dxy": b["dxy"] / out_zoom}
    dr = (1 - b["dxy"]/a["dxy"])*100 if a["dxy"] else 0.0
    ar = (1 - b["da_std"]/a["da_std"])*100 if a["da_std"] else 0.0
    print(f"{'':8s} {'translation':>13s} {'rotation':>12s}")
    print(f"{'input':8s} {a['dxy']:10.2f} px {a['da_std']:9.2f} deg")
    print(f"{'output':8s} {b['dxy']:10.2f} px {b['da_std']:9.2f} deg")
    print(f"{'reduced':8s} {dr:10.1f} %  {ar:9.1f} %")
    return {"in": a, "out": b, "dxy_red": dr, "da_red": ar}


def _trajectory(path, n=300):
    st = OnlineStabilizer(StabConfig(crop_ratio=0.0, smooth_alpha=0.0))
    src = VideoFileSource(path)
    m, i = [], 0
    while i < n:
        f = src.read()
        if f is None:
            break
        sf = st.process(f)
        if sf.motion.valid:
            m.append(sf.motion.as_array())
        i += 1
    src.release()
    return np.cumsum(np.array(m), axis=0)


def _highpass(x, w=15):
    pad = np.pad(x, ((w//2, w//2), (0, 0)), mode="edge")
    return x - sliding_window_view(pad, w, axis=0).mean(axis=-1)


def hf_score(path, cfg, n=300, out_dir="hf"):
    """High-frequency suppression: the metric that matches what the eye sees.

    Strips the low-frequency component (the deliberate camera motion) from
    both input and output, then compares the standard deviation of what is
    left. Returns (x %, y %, saturation %).
    """
    r = stabilize_clip(path, cfg, out_dir=out_dir, max_frames=n,
                       side_by_side=False, to_h264=False, quiet=True)
    z = 1/(1-2*cfg.crop_ratio)
    a = _highpass(_trajectory(path, n))
    b = _highpass(_trajectory(r["out"], n)) / z
    c = cv2.VideoCapture(path)
    W, H = int(c.get(3)), int(c.get(4))
    c.release()
    mx, my = cfg.crop_ratio*W*0.95, cfg.crop_ratio*H*0.95
    co = r["corrections"]
    sat = max((np.abs(co[:, 0]) >= mx*.98).mean(),
              (np.abs(co[:, 1]) >= my*.98).mean())
    return (100*(1-np.std(b[:, 0])/np.std(a[:, 0])),
            100*(1-np.std(b[:, 1])/np.std(a[:, 1])), 100*sat)


def evaluate_gt(gt_path, result, baseline=None, verbose=True):
    """How much of the injected shake came back out.

    `baseline` is the same clip stabilized *without* injected shake. Subtracting
    it removes the source footage's own shake, which otherwise counts as error.
    Note this assumes the system is linear, so it stops being valid once the
    correction saturates -- a clip whose deliberate motion already fills the
    crop budget will produce meaningless (sometimes negative) numbers here.
    """
    gt = np.load(gt_path)
    corr = result["corrections"]
    n = min(len(gt), len(corr))
    gt, corr = gt[:n], corr[:n]
    resid = gt + corr
    if baseline is not None:
        b = baseline["corrections"]
        m = min(n, len(b))
        gt, corr, resid, n = gt[:m], corr[:m], resid[:m] - b[:m], m
    before, after = np.std(gt[:, :2], axis=0), np.std(resid[:, :2], axis=0)
    ba, aa = math.degrees(np.std(gt[:, 2])), math.degrees(np.std(resid[:, 2]))
    out = {"n": n, "baseline": baseline is not None,
           "x_before": float(before[0]), "x_after": float(after[0]),
           "y_before": float(before[1]), "y_after": float(after[1]),
           "a_before": ba, "a_after": aa,
           "x_red": float((1-after[0]/before[0])*100) if before[0] else 0.0,
           "y_red": float((1-after[1]/before[1])*100) if before[1] else 0.0,
           "a_red": float((1-aa/ba)*100) if ba else 0.0,
           "gt": gt, "resid": resid, "corr": corr}
    if verbose:
        tag = "baseline subtracted" if baseline is not None else "no baseline"
        print(f"ground truth, {n} frames, {tag}")
        print(f"{'axis':>6s} {'injected':>10s} {'residual':>10s} {'suppressed':>11s}")
        print(f"{'x':>6s} {out['x_before']:9.2f}px {out['x_after']:9.2f}px {out['x_red']:10.1f}%")
        print(f"{'y':>6s} {out['y_before']:9.2f}px {out['y_after']:9.2f}px {out['y_red']:10.1f}%")
        print(f"{'angle':>6s} {out['a_before']:9.2f}d  {out['a_after']:9.2f}d  {out['a_red']:10.1f}%")
    return out


def show(path, width=960):
    """Play a clip inline. Left half raw, right half stabilized."""
    from base64 import b64encode
    from IPython.display import HTML
    mb = os.path.getsize(path)/1e6
    if mb > 60:
        print(f"warning: {mb:.0f} MB embedded; lower max_frames")
    d = b64encode(open(path, "rb").read()).decode()
    return HTML(f'<video width={width} controls loop>'
                f'<source src="data:video/mp4;base64,{d}" type="video/mp4"></video>')


print("Tools loaded.")

"""### A3. Plots and batch runner

"""

"""Plotting helpers for the notebook."""

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt


def summary_table(results):
    print(f"{'clip':12s} {'resolution':>11s} {'frames':>7s} {'ms':>7s} {'p95':>7s} "
          f"{'FPS':>6s} {'transl.':>9s} {'rot.':>8s} {'sat_x':>7s} {'sat_y':>7s}")
    print("-" * 92)
    for r in results.values():
        rot = "n/a" if r.get("rot_valid") is False else f"{r['da_red']:7.1f}%"
        print(f"{r['name']:12s} {r['res']:>11s} {r['frames']:7d} {r['ms']:7.2f} "
              f"{r['ms_p95']:7.2f} {r['fps']:6.1f} {r['dxy_red']:8.1f}% "
              f"{rot:>8s} {r['sat_x']:6.1f}% {r['sat_y']:6.1f}%")
    print("-" * 92)
    print("transl./rot. = end-to-end suppression, zoom corrected")
    print("sat_*        = share of frames where the correction hit the crop limit")
    print("rot. = n/a   = clip has < 0.2 deg of rotation; the ratio is noise")


def plot_all(results, cfg):
    names = list(results)
    idx = np.arange(len(names))
    w = .38
    fig, ax = plt.subplots(2, 2, figsize=(15, 9))
    fig.suptitle(f"alpha={cfg.smooth_alpha}, crop={cfg.crop_ratio}, "
                 f"adaptive={cfg.adaptive}", fontsize=13, fontweight="bold")

    a = ax[0, 0]
    b1 = a.bar(idx-w/2, [results[n]["dxy_red"] for n in names], w,
               label="translation", color="royalblue", alpha=.85)
    b2 = a.bar(idx+w/2, [results[n]["da_red"] for n in names], w,
               label="rotation", color="darkorange", alpha=.85)
    for bs in (b1, b2):
        for bar in bs:
            a.text(bar.get_x()+bar.get_width()/2, bar.get_height(),
                   f"{bar.get_height():.0f}", ha="center", va="bottom", fontsize=8)
    a.set_title("End-to-end suppression"); a.set_ylabel("%")
    a.set_xticks(idx); a.set_xticklabels(names); a.legend(fontsize=8)
    a.grid(alpha=.3, axis="y")

    a = ax[0, 1]
    a.bar(idx-w/2, [results[n]["sat_x"] for n in names], w, label="x",
          color="royalblue", alpha=.85)
    a.bar(idx+w/2, [results[n]["sat_y"] for n in names], w, label="y",
          color="seagreen", alpha=.85)
    a.axhline(10, ls=":", c="red", lw=1.3, label="10% threshold")
    a.set_title("Frames at the crop limit"); a.set_ylabel("% of frames")
    a.set_xticks(idx); a.set_xticklabels(names); a.legend(fontsize=8)
    a.grid(alpha=.3, axis="y")

    a = ax[1, 0]
    for n in names:
        t = results[n]["times"]
        a.plot(np.arange(len(t)), t, lw=.8, alpha=.75, label=n)
    a.axhline(33.33, ls=":", c="red", lw=1.4, label="30 FPS budget")
    a.set_title("Per-frame processing time")
    a.set_xlabel("frame"); a.set_ylabel("ms"); a.legend(fontsize=8); a.grid(alpha=.3)

    a = ax[1, 1]
    for n in names:
        co = results[n]["corrections"]
        a.plot(np.hypot(co[:, 0], co[:, 1]), lw=1.0, alpha=.8, label=n)
    a.set_title("Magnitude of the applied correction")
    a.set_xlabel("frame"); a.set_ylabel("pixels"); a.legend(fontsize=8); a.grid(alpha=.3)

    plt.tight_layout(); plt.show()


def plot_trajectory(path, cfg, max_frames=300):
    """Raw vs smoothed trajectory. The shaded gap is the correction; the dashed
    red lines are the crop limit. If the correction rides the limit, crop_ratio
    is too small for that clip."""
    src = VideoFileSource(path)
    stab = OnlineStabilizer(cfg)
    traj, sm, n = [], [], 0
    while n < max_frames:
        f = src.read()
        if f is None:
            break
        stab.process(f)
        traj.append(stab.traj.copy())
        sm.append(stab.smooth.copy())
        n += 1
    src.release()
    traj, sm = np.array(traj), np.array(sm)
    W, H = stab.size
    lim = [cfg.crop_ratio*W*0.95, cfg.crop_ratio*H*0.95]
    labels = ["x (px)", "y (px)", "angle (deg)"]
    fig, axes = plt.subplots(3, 1, figsize=(12, 8), sharex=True)
    for i, a in enumerate(axes):
        t = np.degrees(traj[:, i]) if i == 2 else traj[:, i]
        s = np.degrees(sm[:, i]) if i == 2 else sm[:, i]
        a.plot(t, lw=1.0, alpha=.75, label="raw trajectory")
        a.plot(s, lw=1.8, label="smoothed (applied)")
        a.fill_between(range(len(t)), t, s, alpha=.18, label="correction")
        if i < 2:
            a.plot(t+lim[i], "--", lw=.7, c="red", alpha=.5)
            a.plot(t-lim[i], "--", lw=.7, c="red", alpha=.5, label="crop limit")
        a.set_ylabel(labels[i]); a.legend(fontsize=8, loc="upper right"); a.grid(alpha=.3)
    axes[-1].set_xlabel("frame")
    fig.suptitle(f"{os.path.basename(path)} — alpha={cfg.smooth_alpha}, "
                 f"crop={cfg.crop_ratio}")
    plt.tight_layout(); plt.show()


print("Plots loaded.")


"""Batch runner: same config across every clip so comparisons are fair."""

import cv2
import numpy as np


ROT_MIN_DEG = 0.2      # below this the rotation ratio is noise, not signal


def run_all(clips, cfg, max_frames=None):
    z = 1 / (1 - 2*cfg.crop_ratio)
    results = {}
    for name, path in clips.items():
        print(f"[{name}] running...", flush=True)
        r = stabilize_clip(path, cfg, out_dir="out", max_frames=max_frames,
                           side_by_side=True, quiet=True)
        n = r["frames"]
        a = measure_motion(path, n)
        b = measure_motion(r["out"], n, half="right")
        b = {**b, "dxy": b["dxy"] / z}          # output is zoomed
        c = cv2.VideoCapture(path)
        W, H = int(c.get(3)), int(c.get(4))
        c.release()
        mx, my = cfg.crop_ratio*W*0.95, cfg.crop_ratio*H*0.95
        co = r["corrections"]
        r.update({
            "name": name, "in_path": path, "zoom": z, "m_in": a, "m_out": b,
            "dxy_red": (1 - b["dxy"]/a["dxy"])*100 if a["dxy"] else 0.0,
            "da_red": (1 - b["da_std"]/a["da_std"])*100 if a["da_std"] else 0.0,
            "rot_valid": a["da_std"] >= ROT_MIN_DEG,
            "sat_x": float((np.abs(co[:, 0]) >= mx*0.98).mean()*100),
            "sat_y": float((np.abs(co[:, 1]) >= my*0.98).mean()*100),
        })
        results[name] = r
    print("done.")
    return results


print("Runner loaded.")

"""---
## B. Handheld benchmarks

`meshflow` and `ostrich` download automatically. Drop `running.mp4` and any of
your own recordings in the file panel.

"""

import os

CLIPS = {}
CLIPS["meshflow"] = download_sample("meshflow")   # MeshFlow ECCV 2016 sample
CLIPS["ostrich"] = download_sample("ostrich")     # handheld

for extra in ("running.mp4",):                    # drop your own clips here
    if os.path.exists(extra):
        CLIPS[os.path.splitext(extra)[0]] = extra
    else:
        print(f"note: {extra} not found, skipping")

print()
for n, p in CLIPS.items():
    c = cv2.VideoCapture(p)
    print(f"{n:12s} {int(c.get(3))}x{int(c.get(4))}  {c.get(5):4.1f}fps  "
          f"{int(c.get(7)):5d} frames")
    c.release()

"""### Settings

One config for every clip, otherwise the comparison isn't fair. These come from
the sweeps in the appendix: `crop_ratio=0.08` sits at the knee of the
crop-versus-suppression curve, and `max_angle_deg=1.0` stops rotation from
eating the corner budget that translation needs.

"""

CFG = StabConfig(
    smooth_alpha=0.92,
    crop_ratio=0.08,       # 16% of the frame, zoom 1.19x
    adaptive=False,
    max_angle_deg=3.0,
)
MAX_FRAMES = 300

print(f"alpha={CFG.smooth_alpha}  crop={CFG.crop_ratio}  "
      f"zoom={1/(1-2*CFG.crop_ratio):.3f}  adaptive={CFG.adaptive}")

RESULTS = run_all(CLIPS, CFG, MAX_FRAMES)

"""### Results

Two columns decide how to read the rest. `sat_x`/`sat_y` above 10% means the
correction is hitting the crop limit and `crop_ratio` is the binding constraint,
not the filter. Rotation reads `n/a` when a clip barely rotates -- dividing a
small number by a small number measures noise.

"""

summary_table(RESULTS)

plot_all(RESULTS, CFG)

"""### Videos

Left raw, right stabilized.

"""

for n, r in RESULTS.items():
    print(f"\n=== {n}  ({r['res']}, translation -{r['dxy_red']:.0f}%, "
          f"rotation -{r['da_red']:.0f}%) ===")
    display(show(r["out"]))

"""### One clip in detail

"""

CLIP = "meshflow"
plot_trajectory(CLIPS[CLIP], CFG, MAX_FRAMES)

"""---
## C. Target profile: narrow-band vibration

The handheld clips are the wrong data class for a camera bolted to an aircraft.
A hand shakes across 0-20 Hz and overlaps the deliberate motion; a rotor or
engine produces a narrow band with a clear peak, which is exactly what a
low-pass separates cleanly.

Publicly available drone footage is almost all gimbal-stabilized, so the
vibration we want to measure has already been removed in hardware. That turns
out to be useful: a stabilized clip is a clean base to inject a known vibration
into. Real aerial imagery, exact ground truth, and a frequency we can sweep.

"""

"""
Narrow-band vibration benchmark.

The handheld clips (meshflow, ostrich, running) are the wrong data class for a
vehicle-mounted camera. A human hand shakes across a broad band, 0-20 Hz, which
overlaps the deliberate motion and is the hardest case an IIR low-pass can face.
A rotor or engine produces a *narrow* band with a clear peak, which is the
easiest case. Measuring only on handheld footage understates what the method
will do on the target platform.

Publicly available drone footage is almost all gimbal-stabilized, so the
vibration we want to measure has already been removed in hardware. Injecting a
known narrow-band vibration into real footage is the practical alternative: real
texture and lighting, exact ground truth, and a frequency we can sweep.

Caveat worth stating in any report that uses this: at 30 fps only components
below 15 Hz are observable. Real rotor vibration typically sits well above that
and will alias into the visible band as broadband noise -- which is the hard
case again. Frame rate, exposure time and mechanical isolation are decisions
that come before any of this code.
"""

import math
import os

import numpy as np
import cv2



def inject_vibration(src_path, out_path=None, freq=6.0, amp=8.0,
                     bandwidth=0.3, rot_amp=0.0, fps=None,
                     max_frames=300, seed=0):
    """Add narrow-band vibration of known frequency and amplitude.

    freq       : centre frequency in Hz (rotor/engine fundamental)
    amp        : peak displacement in pixels
    bandwidth  : 0 = pure tone; 0.3-1.0 spreads energy into neighbouring
                 frequencies, which is closer to a real machine
    rot_amp    : peak roll in degrees, if the mount transmits rotation too
    Returns (video path, ground-truth .npy path)
    """
    rng = np.random.default_rng(seed)
    if out_path is None:
        b, e = os.path.splitext(src_path)
        out_path = f"{b}_vib{freq:g}Hz_a{amp:g}{e}"

    src = VideoFileSource(src_path)
    W, H = src.width, src.height
    fps = fps or src.fps
    w = cv2.VideoWriter(out_path, cv2.VideoWriter_fourcc(*"mp4v"), fps, (W, H))

    gt, i = [], 0
    side = (freq * 0.8, freq * 1.25)          # sidebands
    while True:
        f = src.read()
        if f is None or (max_frames and i >= max_frames):
            break
        t = i / fps
        jx = amp * math.sin(2 * math.pi * freq * t)
        jy = amp * math.sin(2 * math.pi * freq * t + 1.1)
        ja = rot_amp * math.sin(2 * math.pi * freq * t + 0.4)
        for k, f2 in enumerate(side):
            jx += bandwidth * amp * math.sin(2 * math.pi * f2 * t + k)
            jy += bandwidth * amp * math.sin(2 * math.pi * f2 * t + k + 0.7)

        M = cv2.getRotationMatrix2D((W / 2.0, H / 2.0), ja, 1.0)
        M[0, 2] += jx
        M[1, 2] += jy
        w.write(cv2.warpAffine(f.image, M, (W, H),
                               borderMode=cv2.BORDER_REPLICATE))
        # store the matrix parameters, not jx/jy -- rotation about the centre
        # shows up inside tx/ty and the estimator measures it there
        gt.append([float(M[0, 2]), float(M[1, 2]),
                   float(math.atan2(M[1, 0], M[0, 0]))])
        i += 1
    w.release()
    src.release()
    gt_path = out_path + ".gt.npy"
    np.save(gt_path, np.array(gt))
    return out_path, gt_path


def vibration_sweep(src_path, cfg, freqs=(2, 4, 6, 8, 12), amp=8.0,
                    bandwidth=0.3, n=300, hf_fn=None):
    """Suppression as a function of vibration frequency.

    Pass hf_fn=hf_score (from the notebook) to reuse the same metric everything
    else is measured with.
    """
    rows = []
    print(f"{'freq':>7s} {'HF x':>8s} {'HF y':>8s} {'sat':>6s}")
    for fr in freqs:
        vid, _ = inject_vibration(src_path, freq=fr, amp=amp,
                                  bandwidth=bandwidth, max_frames=n)
        x, y, s = hf_fn(vid, cfg, n)
        print(f"{fr:5.1f}Hz {x:7.1f}% {y:7.1f}% {s:5.0f}%")
        rows.append({"freq": fr, "hf_x": x, "hf_y": y, "sat": s, "clip": vid})
    return rows

"""### Load the clips

Download a few from Pexels or Pixabay. Pick different scene types -- city and
forest give plenty of corners, water and snow give almost none, and the
difference turns out to matter more than anything in the config.

"""

DRONE = {
    "city":   "drone-city.mp4",
    "forest": "drone-forest.mp4",
    "sea":    "drone-sea.mp4",
    "village":  "drone-village.mp4",      # gerçek adı neyse
}
DRONE = {k: v for k, v in DRONE.items() if os.path.exists(v)}
print(DRONE)

"""### Frequency sweep

Suppression against vibration frequency, per scene.

"""

cfg = StabConfig(smooth_alpha=0.92, crop_ratio=0.08,
                 adaptive=False, max_angle_deg=1.0)
N = 120                     # 250 yerine
FREQS = (6,)                # tek frekans, orta bant

for name, path in DRONE.items():
    c = cv2.VideoCapture(path)
    W, H = int(c.get(3)), int(c.get(4))
    c.release()
    print(f"\n=== {name} ({W}x{H}) ===", flush=True)
    vibration_sweep(path, cfg, freqs=FREQS, amp=8.0,
                    bandwidth=0.3, n=N, hf_fn=hf_score)

"""### Does the clip hold still on its own?

A gimbal-stabilized clip should measure close to zero frame-to-frame motion.
Where it doesn't, optical flow is tracking the scene rather than the camera --
waves, moving foliage -- and every suppression figure for that clip has a broken
denominator.

"""

for name in ("city", "forest", "village", "sea"):
    print(f"{name:8s}", {k: round(v,2) for k,v in measure_motion(DRONE[name], 120).items()})

"""### Plots

"""

"""Plots for the drone / narrow-band vibration benchmark."""

import os
import numpy as np
import cv2
import matplotlib.pyplot as plt

def plot_frequency_response(rows, title=None):
    """Suppression against vibration frequency.

    The shape is the argument: an EMA is a low-pass, so the further the
    vibration sits above the deliberate motion, the cleaner the separation.
    Handheld footage has no such separation, which is why it scores worse.
    """
    f = [r["freq"] for r in rows]
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.plot(f, [r["hf_x"] for r in rows], "o-", lw=2, label="x")
    ax.plot(f, [r["hf_y"] for r in rows], "s-", lw=2, label="y")
    ax.axhspan(0, 70, color="crimson", alpha=.06)
    ax.axhspan(70, 100, color="seagreen", alpha=.06)
    ax.set_xlabel("vibration frequency (Hz)")
    ax.set_ylabel("high-frequency suppression (%)")
    ax.set_ylim(0, 100)
    ax.set_title(title or "Suppression vs vibration frequency")
    ax.legend(); ax.grid(alpha=.3)
    for r in rows:
        ax.annotate(f"{r['hf_x']:.0f}", (r["freq"], r["hf_x"]),
                    textcoords="offset points", xytext=(0, 8),
                    ha="center", fontsize=8)
    plt.tight_layout(); plt.show()


def plot_scene_comparison(results, title=None):
    """Suppression per scene, next to the clip's own measured motion.

    These two move together for a reason. On a gimbal-stabilized clip the
    measured base motion should be near zero; where it isn't, optical flow is
    tracking the scene rather than the camera, and the suppression figure for
    that clip is measuring a broken denominator.

    results: {name: {"hf_x":.., "hf_y":.., "base":..}}
    """
    names = list(results)
    idx = np.arange(len(names)); w = .35
    fig, ax = plt.subplots(1, 2, figsize=(14, 5))

    a = ax[0]
    b1 = a.bar(idx - w/2, [results[n]["hf_x"] for n in names], w,
               label="x", color="royalblue", alpha=.85)
    b2 = a.bar(idx + w/2, [results[n]["hf_y"] for n in names], w,
               label="y", color="seagreen", alpha=.85)
    for bs in (b1, b2):
        for bar in bs:
            a.text(bar.get_x()+bar.get_width()/2, bar.get_height(),
                   f"{bar.get_height():.0f}", ha="center", va="bottom", fontsize=8)
    a.set_title("Suppression by scene"); a.set_ylabel("%")
    a.set_xticks(idx); a.set_xticklabels(names); a.legend(fontsize=8)
    a.set_ylim(0, 105); a.grid(alpha=.3, axis="y")

    a = ax[1]
    base = [results[n]["base"] for n in names]
    bars = a.bar(idx, base, .5, color="darkorange", alpha=.85)
    for bar, v in zip(bars, base):
        a.text(bar.get_x()+bar.get_width()/2, bar.get_height(), f"{v:.1f}",
               ha="center", va="bottom", fontsize=9)
    a.axhline(3, ls=":", c="red", lw=1.3,
              label="above this, flow is tracking the scene")
    a.set_title("Clip's own measured motion\n(gimbal-stabilized: should be ~0)")
    a.set_ylabel("px / frame")
    a.set_xticks(idx); a.set_xticklabels(names); a.legend(fontsize=8)
    a.grid(alpha=.3, axis="y")

    fig.suptitle(title or "Scene texture drives estimation quality",
                 fontsize=13, fontweight="bold")
    plt.tight_layout(); plt.show()


def plot_correction_trace(path, cfg, freq=6.0, amp=8.0, n=120, label=None):
    """Applied correction over time, against the crop budget.

    A healthy trace oscillates around zero at the vibration frequency. A trace
    that ramps up and stays there is following something slow -- scene motion,
    not shake.
    """
    vid, _ = inject_vibration(path, freq=freq, amp=amp,
                              bandwidth=0.3, max_frames=n)
    r = stabilize_clip(vid, cfg, out_dir="trace", max_frames=n,
                       side_by_side=False, to_h264=False, quiet=True)
    co = r["corrections"]
    c = cv2.VideoCapture(path); W, H = int(c.get(3)), int(c.get(4)); c.release()
    mx, my = cfg.crop_ratio*W*0.95, cfg.crop_ratio*H*0.95

    fig, ax = plt.subplots(figsize=(11, 4))
    ax.plot(co[:, 0], lw=1.2, label="x correction")
    ax.plot(co[:, 1], lw=1.2, label="y correction")
    ax.axhline(amp, ls=":", c="gray", lw=1, label=f"injected amplitude ({amp:g}px)")
    ax.axhline(-amp, ls=":", c="gray", lw=1)
    ax.axhline(mx, ls="--", c="red", lw=.8, label=f"crop limit x ({mx:.0f}px)")
    ax.axhline(-mx, ls="--", c="red", lw=.8)
    ax.set_xlabel("frame"); ax.set_ylabel("pixels")
    ax.set_title(label or f"{os.path.basename(path)} — applied correction")
    ax.legend(fontsize=8); ax.grid(alpha=.3)
    plt.tight_layout(); plt.show()
    print(f"peak correction  x={np.abs(co[:,0]).max():.1f}px  "
          f"y={np.abs(co[:,1]).max():.1f}px   injected {amp:g}px")


def plot_spectrum(paths, labels=None, n=200, fps=30.0):
    """Where each clip's energy sits in frequency.

    Narrow-band vibration (a rotor) shows a peak an IIR low-pass can cut
    cleanly. Handheld shake spreads across the band and overlaps the motion
    that has to be kept, which is the hard case.
    """
    labels = labels or [os.path.basename(p) for p in paths]
    fig, ax = plt.subplots(1, 2, figsize=(14, 4.5))
    for p, lb in zip(paths, labels):
        cum = _trajectory(p, n)
        d = np.diff(cum, axis=0)
        for k, axis in enumerate(("x", "y")):
            sig = d[:, k] - d[:, k].mean()
            f = np.abs(np.fft.rfft(sig))
            fr = np.fft.rfftfreq(len(sig), 1/fps)
            ax[k].plot(fr[1:], f[1:] / max(f[1:].max(), 1e-9),
                       lw=1.2, alpha=.85, label=lb)
    for k, axis in enumerate(("x", "y")):
        ax[k].set_title(f"{axis} axis"); ax[k].set_xlabel("Hz")
        ax[k].set_ylabel("normalised amplitude")
        ax[k].legend(fontsize=8); ax[k].grid(alpha=.3)
    fig.suptitle("Frequency content", fontsize=12, fontweight="bold")
    plt.tight_layout(); plt.show()

rows = vibration_sweep(DRONE["city"], cfg, freqs=(2,4,6,8,12),
                       amp=8.0, bandwidth=0.3, n=120, hf_fn=hf_score)
plot_frequency_response(rows, "city — dar bantlı titreşim")

SCENE = {}
for name, path in DRONE.items():
    x, y, s = hf_score(inject_vibration(path, freq=6.0, amp=8.0,
                                        bandwidth=0.3, max_frames=120)[0], cfg, 120)
    SCENE[name] = {"hf_x": x, "hf_y": y,
                   "base": measure_motion(path, 120)["dxy"]}
plot_scene_comparison(SCENE)

plot_correction_trace(DRONE["city"], cfg, freq=6.0, amp=8.0, n=120, label="city")
plot_correction_trace(DRONE["sea"], cfg, freq=6.0, amp=8.0, n=120, label="sea")

plot_spectrum([CLIPS["meshflow"], DRONE["city"]],
              ["meshflow (elde)", "city (drone)"], n=200)

"""### What came out

| scene | base motion | suppression |
|---|---|---|
| city | 0.76 px | 94% |
| forest | 0.65 px | 92% |
| village | 9.72 px | 50-67% |
| sea | 15.54 px | 55% |

Suppression tracks base motion inversely, and that ordering is the finding. On
`city` and `forest` the gimbal did its job, the base is clean, and the numbers
are real. On `sea` the 15.5 px/frame is not the camera -- the gimbal already
removed that -- it is wave motion that optical flow cannot distinguish from
camera motion.

A control run settles it: feeding the untouched `sea` clip through the
stabilizer took its motion from 5.07 to 4.97 px. The code does no harm on
textureless scenes, it just cannot measure. The suppression figure there is
measuring the metric's own failure.

Practical consequence for flight planning: over water, snow or plain sky,
image-based estimation is not dependable and an IMU is needed. A gyro doesn't
care what the scene looks like.

### Control: no vibration injected

A clip that is already stable should come out unchanged.
"""

for name in ("city", "sea"):
    src = cv2.VideoCapture(DRONE[name])
    fps = src.get(cv2.CAP_PROP_FPS) or 30
    w = cv2.VideoWriter(f"{name}_small.mp4", cv2.VideoWriter_fourcc(*"mp4v"),
                        fps, (1280, 720))
    i = 0
    while i < 150:
        ok, f = src.read()
        if not ok: break
        w.write(cv2.resize(f, (1280, 720))); i += 1
    w.release(); src.release()
    print(f"{name}_small.mp4 hazır")

for name in ("city", "sea"):
    r = stabilize_clip(f"{name}_small.mp4", cfg, out_dir=f"nz_{name}",
                       max_frames=120, side_by_side=True, quiet=True)
    print(f"\n=== {name} — titreşim yok, sol ham sağ 'stabilize' ===")
    display(show(r["out"]))

# Drone klipleri: titreşimli vs stabilize
for name in ("city", "forest", "village", "sea"):
    src = cv2.VideoCapture(DRONE[name])
    fps = src.get(cv2.CAP_PROP_FPS) or 30
    small = f"{name}_small.mp4"
    w = cv2.VideoWriter(small, cv2.VideoWriter_fourcc(*"mp4v"), fps, (1280, 720))
    i = 0
    while i < 150:
        ok, f = src.read()
        if not ok: break
        w.write(cv2.resize(f, (1280, 720))); i += 1
    w.release(); src.release()

    vid, _ = inject_vibration(small, freq=6.0, amp=8.0, bandwidth=0.3, max_frames=120)
    r = stabilize_clip(vid, cfg, out_dir=f"vw_{name}", max_frames=120,
                       side_by_side=True, quiet=True)
    print(f"\n=== {name} — sol: titreşimli   sağ: stabilize ===")
    display(show(r["out"]))

"""---
## D. Deployment

Only section A1 goes to the device. Pair it with `run_camera.py` and swap
`VideoFileSource` for `CsiCameraSource`.

```bash
gst-launch-1.0 nvarguscamerasrc num-buffers=30 ! fakesink   # camera alive?
python3 record_clips.py --sensor-id 0 --seconds 30          # real footage
sudo nvpmodel -m 0 && sudo jetson_clocks
python3 run_camera.py --sensor-id 0 --frames 900 --no-display
```

Measured on an Orin NX, against the same clips in Colab:

| clip | Colab | Orin NX |
|---|---|---|
| meshflow | 10.5 ms | 10.4 ms |
| ostrich | 15.1 ms | 14.9 ms |
| running | 6.5 ms | 9.0 ms |

They line up, so the 1080p figure measured in Colab (17 ms, p95 27 ms) is
representative of the device. One camera fits inside a 30 FPS budget; two will
need the warp on the GPU.

Watch p95, not the mean -- 30 FPS means every frame under 33.3 ms, and a 20 ms
average with a 40 ms p95 still drops frames. Close VS Code while measuring; its
server takes a real bite out of an Orin.

Three decisions that come before any more code:

**Frame rate.** At 30 fps only components below 15 Hz are observable. Rotor
vibration typically sits well above that and aliases into the visible band as
broadband noise -- back to the hard case. Either the frame rate goes up or the
vibration gets isolated mechanically.

**Global shutter.** High-frequency vibration plus row-by-row readout produces
jello, and the quadrant test in the appendix shows a global affine transform
cannot undo it.

**IMU.** An aircraft or drone already carries one. Gyro data measures rotation
far more accurately than image-based estimation and works on textureless
scenes. `process()` takes an `external_correction` for exactly this.

---
# Appendix — where the settings came from

None of this runs as part of the main flow. It is kept because the reasoning
matters more than the numbers, and because several of these experiments found
real bugs.

## A. Which metric to trust

End-to-end suppression counts the deliberate camera motion we are supposed to
keep, so on pan-heavy footage it cannot approach 100%. Splitting the trajectory
into intentional and shake components makes that concrete -- on one Jetson
recording 97% of the movement was intentional, which is why 40% looked bad when
it was near the ceiling.

`hf_score` strips the low-frequency part first. That is the number worth tuning
against, and switching to it reversed several conclusions.
"""

from numpy.lib.stride_tricks import sliding_window_view

def motion_split(path, n=300):
    """Split the trajectory into intentional motion and shake."""
    cum = _trajectory(path, n)
    def lowpass(x, w=31):
        pad = np.pad(x, ((w//2, w//2), (0, 0)), mode="edge")
        return sliding_window_view(pad, w, axis=0).mean(axis=-1)
    lp = lowpass(cum); hp = cum - lp
    print(f"{os.path.basename(path)}")
    for i, lbl in enumerate(["x", "y"]):
        low, high = np.std(lp[:, i]), np.std(hp[:, i])
        print(f"  {lbl}: intentional={low:7.1f}px  shake={high:6.1f}px"
              f"  -> shake is {100*high**2/(high**2+low**2):.0f}% of the energy")

for n, p in CLIPS.items():
    motion_split(p, 300)

"""## B. Crop ratio

Every pixel of crop is field of view given up, so this is the trade-off that
needs an actual decision. The curve knees around 0.08: below it suppression
falls off quickly, above it each extra 4% of frame buys about 2 points.

"""

for cr in (0.03, 0.04, 0.05, 0.06, 0.08, 0.10, 0.14):
    row = f"crop={cr:<5} zoom={1/(1-2*cr):.2f}x  loss={200*cr:3.0f}%  "
    for n in ("meshflow", "running"):
        if n not in CLIPS: continue
        x, y, s = hf_score(CLIPS[n], StabConfig(smooth_alpha=0.92, crop_ratio=cr,
                                                adaptive=False, max_angle_deg=3.0))
        row += f"| {n}: x={x:5.1f} y={y:5.1f} sat={s:3.0f}% "
    print(row)

"""## C. Smoothing strength

Two clips want opposite things. `meshflow` improves as alpha goes up; `running`
gets worse, because the camera moves fast enough that the extra lag fills the
crop budget and the correction saturates.

Worth noting what this sweep is really measuring. At 30 fps an EMA's cutoff is
`fs(1-a)/(2*pi*a)` -- 0.42 Hz at alpha=0.92, 0.84 Hz at 0.85. A running stride
sits at 2-3 Hz, well above both, so in frequency-response terms the two settings
are nearly identical. The fact that the sweep moves the numbers at all means it
is measuring saturation behaviour, not filtering.

"""

for al in (0.85, 0.92, 0.95):
    row = f"alpha={al}  "
    for n in ("meshflow", "running"):
        if n not in CLIPS: continue
        x, y, s = hf_score(CLIPS[n], StabConfig(smooth_alpha=al, crop_ratio=0.08,
                                                adaptive=False, max_angle_deg=3.0))
        row += f"| {n}: x={x:5.1f} y={y:5.1f} sat={s:3.0f}% "
    print(row)

"""## D. Rotation budget

Rotating about the centre displaces a corner by roughly `r*theta`, and that
displacement comes out of the same crop budget translation uses. A generous
`max_angle_deg` quietly starves translation even on clips that barely rotate.

Measured rotation on these clips runs 0.28-1.19 degrees, so the original ceiling
of 3.0 was reserving budget that never got used. Dropping it improved
suppression on all three. It is a trade, not free: below about 1.0 the rotation
figure itself starts to fall.

"""

for n in ("meshflow", "ostrich"):
    for ma in (0.5, 1.0, 3.0):
        cfg = StabConfig(smooth_alpha=0.92, crop_ratio=0.08,
                         adaptive=False, max_angle_deg=ma)
        x, y, s = hf_score(CLIPS[n], cfg, 300)
        print(f"{n:10s} max_angle={ma}  HF x={x:5.1f}  y={y:5.1f}")

"""## E. Other smoothers

An EMA lags behind sustained motion by roughly `v * a/(1-a)`, and that lag eats
crop budget. Several filters that shouldn't have the problem were tried:
alpha-beta and alpha-beta-gamma (constant velocity and acceleration, no
steady-state error) and cascaded EMAs (sharper cutoff).

None beat the plain EMA. The cascades push saturation up because the extra
stages add their own delay.

"""

def set_smoother(kind):
    """kind: 'ema' | 'ab' (constant velocity) | 'ema2' (cascaded)"""
    def _step(self, mx, my):
        cfg = self.cfg; al = cfg.smooth_alpha
        if kind == "ab":
            if not hasattr(self, "_vel"): self._vel = np.zeros(3)
            g = 1-al; bg = g*g/(2-g)
            pred = self.smooth + self._vel; res = self.traj - pred
            self.smooth = pred + g*res; self._vel = self._vel + bg*res
        elif kind == "ema2":
            if not hasattr(self, "_s1"): self._s1 = np.zeros(3)
            self._s1 = al*self._s1 + (1-al)*self.traj
            self.smooth = al*self.smooth + (1-al)*self._s1
        else:
            self.smooth = al*self.smooth + (1-al)*self.traj
        corr = self.smooth - self.traj
        ma = math.radians(cfg.max_angle_deg)
        corr = self._soft_limit(corr, mx, my, ma)
        self.smooth += cfg.windup_leak * ((self.traj + corr) - self.smooth)
        return corr
    OnlineStabilizer._smooth_step = _step

P = CLIPS["meshflow"]
for kind in ("ema", "ab", "ema2"):
    for al in (0.85, 0.92):
        set_smoother(kind)
        x, y, s = hf_score(P, StabConfig(smooth_alpha=al, crop_ratio=0.08,
                                         adaptive=False, max_angle_deg=3.0))
        print(f"{kind:5s} alpha={al}  x={x:5.1f}  y={y:5.1f}  sat={s:3.0f}%")
set_smoother("ema")   # back to default

"""## F. Ground truth

Inject shake of known strength, check how much comes back out. This is the
cleanest signal that the core is correct, and it is how the rotation-sign and
zoom-scaling bugs were both caught.

One caveat: subtracting the baseline assumes the system is linear, so it breaks
once the correction saturates. A clip whose own motion already fills the crop
budget produces meaningless, sometimes negative, numbers here.

"""

P = CLIPS["meshflow"]
cfg = StabConfig(smooth_alpha=0.92, crop_ratio=0.10,
                 adaptive=False, max_angle_deg=6.0)

shaken, gt_path = add_shake(P, amp=15.0, rot=2.0, max_frames=300)
base = stabilize_clip(P, cfg, out_dir="gt_base", max_frames=300,
                      side_by_side=False, to_h264=False, quiet=True)
res = stabilize_clip(shaken, cfg, max_frames=300, quiet=True)
evaluate_gt(gt_path, res, baseline=base)

"""### Rotation on its own

Rotation suppression sits below translation, so it was isolated with a pure
rotation injection (`amp=0`). Around 73-74% on both clips, which rules out a
sign or composition error in the warp -- it is the ceiling, not a bug.

"""

for clip in ("meshflow", "ostrich"):
    p = CLIPS[clip]
    sh, gtp = add_shake(p, amp=0.0, rot=3.0, max_frames=250)
    cfg = StabConfig(smooth_alpha=0.92, crop_ratio=0.10,
                     adaptive=False, max_angle_deg=6.0)
    base = stabilize_clip(p, cfg, out_dir=f"pr_{clip}", max_frames=250,
                          side_by_side=False, to_h264=False, quiet=True)
    r = stabilize_clip(sh, cfg, out_dir=f"pr2_{clip}", max_frames=250,
                       side_by_side=False, to_h264=False, quiet=True)
    ev = evaluate_gt(gtp, r, baseline=base, verbose=False)
    print(f"{clip:10s} pure rotation suppressed: {ev['a_red']:.1f}%")

"""## G. Where the remaining shake comes from

Split the frame into quadrants and measure each separately. If the quadrants
disagree more than they agree, the leftover motion isn't global and no single
affine transform can remove it -- correcting one corner necessarily breaks
another.

On the Jetson recordings the disagreement exceeded the common motion (116% on
input, 131% on output). That is rolling shutter, parallax, or both, and it is
why parameter tuning stopped helping.

"""

def quadrant_test(path, cfg, n=200):
    r = stabilize_clip(path, cfg, out_dir="quad", max_frames=n,
                       side_by_side=False, to_h264=False, quiet=True)
    for label, vid in [("input", path), ("output", r["out"])]:
        src = VideoFileSource(vid)
        sts = [OnlineStabilizer(StabConfig(crop_ratio=0.0, smooth_alpha=0.0))
               for _ in range(4)]
        acc = [[] for _ in range(4)]
        i = 0
        while i < n:
            f = src.read()
            if f is None: break
            h, w = f.image.shape[:2]
            quads = [(0,h//2,0,w//2), (0,h//2,w//2,w),
                     (h//2,h,0,w//2), (h//2,h,w//2,w)]
            for k, (y0,y1,x0,x1) in enumerate(quads):
                sub = Frame(f.image[y0:y1, x0:x1], f.timestamp, f.index)
                sf = sts[k].process(sub)
                if sf.motion.valid: acc[k].append(sf.motion.as_array()[:2])
            i += 1
        src.release()
        A = [np.array(a) for a in acc]
        m = min(len(a) for a in A)
        A = np.stack([a[:m] for a in A])
        common = A.mean(axis=0)
        spread = np.linalg.norm(A - common, axis=2).mean()
        mag = np.linalg.norm(common, axis=1).mean()
        print(f"{label:7s} common={mag:6.2f}px  spread={spread:6.2f}px  "
              f"ratio={100*spread/max(mag,1e-6):.0f}%")

quadrant_test(CLIPS["meshflow"], CFG)

"""### Estimation health

Inlier counts per clip. Low counts mean the estimate itself is shaky.

"""

def inlier_probe(path, cfg, n=300):
    src = VideoFileSource(path); st = OnlineStabilizer(cfg)
    inl, low, invalid, i = [], 0, 0, 0
    while i < n:
        f = src.read()
        if f is None: break
        sf = st.process(f)
        if sf.motion.valid:
            inl.append(sf.motion.n_inliers)
            if sf.motion.n_inliers < cfg.conf_inliers: low += 1
        else:
            invalid += 1
        i += 1
    src.release()
    inl = np.array(inl)
    print(f"{os.path.basename(path):20s} inlier ort={inl.mean():6.1f} p10={np.percentile(inl,10):5.0f}  "
          f"wgt<1=%{100*low/i:.1f}  geçersiz=%{100*invalid/i:.1f}")

cfg = StabConfig(smooth_alpha=0.92, crop_ratio=0.08, adaptive=False, max_angle_deg=3.0)
for n, p in CLIPS.items():
    inlier_probe(p, cfg)

"""## H. What look-ahead buys

The pipeline is causal by design. That constraint is worth pricing: if a small
buffer bought a lot of quality, it would be worth asking whether zero latency is
really a hard requirement.

`LookaheadStabilizer` changes only the smoothing -- it holds L frames and fits a
centred Gaussian window, so the filter has no phase lag. The cost is exactly L
frames of latency; 3 frames is 100 ms at 30 fps.

An earlier version of this test tied the window width to L and used end-to-end
motion as the metric. Both mistakes made short look-ahead look far worse than it
is, and the conclusion flipped once they were fixed.

"""

"""Look-ahead variant: buffers L frames so the smoother can see the future."""
from collections import deque
import math, time
import numpy as np
import cv2


class LookaheadStabilizer(OnlineStabilizer):
    def __init__(self, cfg=StabConfig(), cam_id=0, lookahead=5, sigma=None):
        super().__init__(cfg, cam_id)
        self.L = int(lookahead)
        self.sigma = sigma if sigma else max(self.L / 2.0, 1.0)
        self.R = max(int(round(3 * self.sigma)), self.L, 1)
        self._buf = deque()
        self._hist = deque(maxlen=self.R + self.L + 1)

    def _weights(self, n, center):
        idx = np.arange(n) - center
        w = np.exp(-0.5 * (idx / self.sigma) ** 2)
        return w / w.sum()

    def process(self, frame, external_correction=None):
        t0 = time.perf_counter()
        cfg = self.cfg
        gray = self._prepare(frame.image)
        motion = Motion()
        need = (self.prev_pts is None or len(self.prev_pts) < cfg.min_tracks
                or self.frame_count % cfg.redetect_interval == 0)
        if self.prev_gray is not None:
            if need:
                self.prev_pts = self._detect(self.prev_gray, keep=self.prev_pts)
            if self.prev_pts is not None and len(self.prev_pts) >= 6:
                p0, p1 = self._track(self.prev_gray, gray, self.prev_pts)
                if p0 is not None:
                    motion = self._estimate(p0, p1)
                    self.prev_pts = p1.reshape(-1, 1, 2).astype(np.float32)
                else:
                    self.prev_pts = None
            else:
                self.prev_pts = None
        if motion.valid:
            w = min(1.0, motion.n_inliers / float(cfg.conf_inliers))
            self.traj += w * motion.as_array()
        self.prev_gray = gray
        self.frame_count += 1
        t_est = (time.perf_counter() - t0) * 1000.0
        self._hist.append(self.traj.copy())
        self._buf.append((frame, motion, t_est, self.traj.copy()))
        if len(self._buf) <= self.L:
            return None
        return self._emit()

    def _emit(self):
        t1 = time.perf_counter()
        frame, motion, t_est, traj_i = self._buf.popleft()
        center = max(min(len(self._hist) - 1 - len(self._buf), len(self._hist) - 1), 0)
        W, H = self.size
        mx = self.cfg.crop_ratio * W * 0.95
        my = self.cfg.crop_ratio * H * 0.95
        T = np.asarray(self._hist)
        smooth = (T * self._weights(len(T), center)[:, None]).sum(axis=0)
        corr = smooth - traj_i
        ma = math.radians(self.cfg.max_angle_deg)
        corr = self._soft_limit(corr, mx, my, ma)
        M = self._warp_matrix(corr)
        for _ in range(6):
            if self._fits(M, W, H): break
            corr *= 0.85
            M = self._warp_matrix(corr)
        out = cv2.warpAffine(frame.image, M, (W, H),
                             flags=self.cfg.interpolation,
                             borderMode=self.cfg.border_mode)
        return StabilizedFrame(out, frame.timestamp, frame.index, frame.cam_id,
                               corr, motion, M,
                               0 if self.prev_pts is None else len(self.prev_pts),
                               t_est + (time.perf_counter() - t1) * 1000.0)

    def flush(self):
        while self._buf:
            yield self._emit()

def run_lookahead(path, cfg, L, sigma, n, out="la_tmp.mp4"):
    src = VideoFileSource(path)
    st = LookaheadStabilizer(cfg, lookahead=L, sigma=sigma)
    W, H = src.width, src.height
    w = cv2.VideoWriter(out, cv2.VideoWriter_fourcc(*"mp4v"), src.fps, (W, H))
    times, corrs, i = [], [], 0
    while i < n:
        f = src.read()
        if f is None: break
        sf = st.process(f)                     # tampon dolana kadar None
        if sf is not None:
            times.append(sf.proc_ms); corrs.append(sf.correction.copy())
            w.write(sf.image)
        i += 1
    for sf in st.flush():                      # sonda tamponu boşalt
        times.append(sf.proc_ms); corrs.append(sf.correction.copy())
        w.write(sf.image)
    w.release(); src.release()
    return out, np.array(times), np.array(corrs)


def hf_of_output(path, out, cfg, corrs, n):
    z = 1/(1-2*cfg.crop_ratio)
    a = _highpass(_trajectory(path, n))
    b = _highpass(_trajectory(out, n)) / z
    c = cv2.VideoCapture(path); W, H = int(c.get(3)), int(c.get(4)); c.release()
    mx, my = cfg.crop_ratio*W*0.95, cfg.crop_ratio*H*0.95
    sat = max((np.abs(corrs[:,0]) >= mx*.98).mean(),
              (np.abs(corrs[:,1]) >= my*.98).mean())
    return (100*(1-np.std(b[:,0])/np.std(a[:,0])),
            100*(1-np.std(b[:,1])/np.std(a[:,1])), 100*sat)


P = CLIPS["meshflow"]
N = 150

print("causal")
best_c = None
for al in (0.85, 0.92, 0.95, 0.97):
    cfg = StabConfig(smooth_alpha=al, crop_ratio=0.08,
                     adaptive=False, max_angle_deg=3.0)
    x, y, s = hf_score(P, cfg, N)
    print(f"  alpha={al:<5}                x={x:5.1f}  y={y:5.1f}  sat={s:3.0f}%")
    if best_c is None or x+y > best_c[0]:
        best_c = (x+y, al, x, y)

print("\nlook-ahead")
cfg = StabConfig(smooth_alpha=0.92, crop_ratio=0.08,
                 adaptive=False, max_angle_deg=3.0)
best_l, LA = {}, {}
for L in (2, 3):
    for sg in (3, 5, 8, 12):
        out, t, co = run_lookahead(P, cfg, L, sg, N, f"la_{L}_{sg}.mp4")
        x, y, s = hf_of_output(P, out, cfg, co, N)
        if L not in best_l or x+y > best_l[L][0]:
            best_l[L] = (x+y, sg, x, y, s, t.mean()); LA[L] = out
for L, (tot, sg, x, y, s, ms) in sorted(best_l.items()):
    print(f"  L={L} ({L*1000//30:3d} ms) sigma={sg:<3}      "
          f"x={x:5.1f}  y={y:5.1f}  sat={s:3.0f}%  ms={ms:.2f}")

bl = max(best_l.items(), key=lambda kv: kv[1][0])
print(f"\nbest causal    : alpha={best_c[1]}  x={best_c[2]:.1f}  y={best_c[3]:.1f}")
print(f"best look-ahead: L={bl[0]} ({bl[0]*1000//30} ms)  "
      f"x={bl[1][2]:.1f}  y={bl[1][3]:.1f}")
print(f"gain           : x +{bl[1][2]-best_c[2]:.1f}  y +{bl[1][3]-best_c[3]:.1f}")

L = 3
SIGMA = 12

# ileri bakış çıktısını ham kareyle yan yana yaz
src = VideoFileSource(P)
st = LookaheadStabilizer(cfg, lookahead=L, sigma=SIGMA)
W, H = src.width, src.height
w = cv2.VideoWriter("la_sbs.mp4", cv2.VideoWriter_fourcc(*"mp4v"), src.fps, (W*2, H))

raws, i = [], 0
while i < N:
    f = src.read()
    if f is None: break
    raws.append(f.image)
    sf = st.process(f)
    if sf is not None:
        w.write(np.hstack([raws[len(raws)-1-L], sf.image]))   # L kare geriden eşle
    i += 1
for sf in st.flush():
    idx = len(raws) - len(list(st._buf)) - 1
    w.write(np.hstack([raws[max(idx, 0)], sf.image]))
w.release(); src.release()

!ffmpeg -y -loglevel error -i la_sbs.mp4 -vcodec libx264 -pix_fmt yuv420p la_sbs_h264.mp4
print(f"left: raw   right: look-ahead L={L} ({L*1000//30} ms delay)")
display(show("la_sbs_h264.mp4"))

"""### Result

On `meshflow`, best causal was 69.4 / 65.6 at alpha=0.95. Look-ahead beat it at
every buffer size: 72.8 / 68.4 at 66 ms, 73.5 / 69.6 at 100 ms, flattening after
that. Per-frame cost is unchanged and nothing saturates, so the only price is
the latency itself.

That turns a design assumption into a question worth asking: is zero latency
required, or was it a default? At 100 ms the answer is worth about 4 points.
Both cameras would take the same delay, so it doesn't complicate stereo sync
either.

## I. Spatially-varying models, tried and rejected

The quadrant test says a global affine transform has hit its ceiling, so two
richer models were tried.

**Strip-based** (rows only, aimed at rolling shutter): no measurable gain,
around 2 points either way on `running`, at 30% more cost. Suggested the
variation is genuinely two-dimensional rather than a pure shear.

**Mesh** (a grid of local motions, in the shape of MeshFlow): on `meshflow` it
lifted vertical suppression from 63% to 70% and pulled the quadrant disagreement
down from 1.43 to 1.32 px, at about 25% more cost. On `running` it gained
nothing.

Neither is in the shipped config. The mesh result is real but narrow, and there
is an architectural catch for stereo: a spatially-varying warp computed
independently per camera breaks epipolar geometry, so a mesh would have to be
estimated jointly and applied identically to both cameras. That decision comes
before adopting it.

The code for both is kept in `strips.py` and `mesh.py` in the repository.

## J. Bugs this process caught

Each was found by a measurement rather than by reading the code, and each moved
the numbers.

**Rotation sign.** `estimateAffinePartial2D` returns `M[1,0] = +sin(theta)`;
`getRotationMatrix2D(theta)` produces `M[1,0] = -sin(theta)`. Measuring with one
and applying with the other roughly doubled the rotation instead of removing it.
A/B on a synthetic clip: input 2.64 degrees, output 4.93 before the fix, 0.67
after.

**Zoom scaling.** The crop-zoom magnifies the image by z, so it magnifies the
motion inside it too, but the correction wasn't scaled to match. A fraction
`(z-1)/z` of every shake survived -- 32% at crop=0.12. Controlled test: 28.4 px
in, 10.3 px out before, 2.1 px after.

**Rotation budget overflow.** Translation was limited per-axis, which ignores
the margin rotation eats at the corners. At crop=0.10 with 6 degrees the frame
overflowed by 53 px and `BORDER_REPLICATE` smeared the edges. All four corners
are now checked against the combined transform.

**Rotation budget starvation.** Separately from the overflow, a `max_angle_deg`
of 3.0 reserved corner budget that the actual rotation (0.28-1.19 degrees) never
used, and the corner check was cutting the whole correction on 83% of frames on
`running`. Dropping the ceiling to 1.0 raised translation suppression from 32%
to 39% on that clip and helped the other two as well.

**Measurement bias.** `compare_motion` compared an unzoomed input against a
zoomed output, so results got *worse* as crop_ratio went up. Correcting for zoom
flattened it: what looked like 51% to 29% across crop 0.06-0.20 was 57%
throughout.

**Confidence weighting.** `traj += w * motion` looks like a confidence filter
but is a truncated estimate -- on a frame with half the required inliers, half
the measured motion never reaches the trajectory, and that error is permanent.
Synthetic check: 100 px of true motion accumulated as 62 px. Now blended toward
a constant-velocity prediction instead of toward zero. It fires on about 1% of
frames on these clips, so it changed nothing here, but it would matter on
footage where tracking degrades.

**Metric choice.** End-to-end motion rewards lag, which made the look-ahead
variant look worse than the causal one and pushed alpha too high. Switching to
high-frequency suppression reversed several conclusions.
"""